version: '3'

services:
  server-nginx:
    container_name: web-server-marisel
    build: infra/web-server/nginx
    ports:
      - "8080:80"
    volumes:
      - ./Project:/var/www/
    tty: true
    networks:
      - marisel-network

  server-mysql:
    container_name: data-base-marisel
    build: infra/data-base/mysql-5.7.22
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: marisel
     MYSQL_DATABASE: marisel
     MYSQL_USER: marisel
     MYSQL_PASSWORD: marisel
    networks:
     - marisel-network

#  server-elasticsearch:
#    container_name: elasticsearch-marisel
#    build: infra/log/elasticsearch
#    ports:
#     - "9200:9200"
#    volumes:
#      - ./infra/log/elasticsearch/els-data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#    networks:
#     - marisel-network

#  server-kibana:
#    container_name: kibana-marisel
#    build: infra/log/kibana
#    ports:
#      - "5601:5601"
#    networks:
#      - marisel-network

#  server-logstash:
#    container_name: logstash-marisel
#    build: infra/log/logstash
#    #tty: true
#    ports:
#      - "5044:5044"
#    networks:
#      - marisel-network

networks:
  marisel-network:
    driver: bridge